apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app.kubernetes.io/name: hello-world
    app.kubernetes.io/version: "1"
 spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world
      app.kubernetes.io/version: "1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world
        app.kubernetes.io/version: "1"
    spec:
      containers:
      - name: hello-world-pod
        image: nginx:latest
        ports: 
        - containerPort: 80

